# Dockerfile for React Web Client (Development)

FROM node:14.5.0

RUN mkdir -p /app/frontend
WORKDIR /app/frontend

COPY package*.json /app/frontend/

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"] 