# Dockerfile for Node Server (Development)

FROM node:14.5.0

RUN npm install -g nodemon

RUN mkdir -p /app/backend
WORKDIR /app/backend


COPY package*.json /app/backend/

RUN npm install

COPY . /app/backend/

CMD ["npm", "start"] 