# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, staging, dev, release/*, feature/*, hotfix/* ]
  pull_request:
    branches: [ master, staging, dev, release/*, feature/*, hotfix/* ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: cd backend
    - run: npm ci
    - run: cd ..
    - run: npm run build --if-present
    - run: npm test
